### ISSUE TITLE
FATAL  [shopware-pwa] There is no default language file for en-GB code, please add translation file to locales folder.[BUG]

### ISSUE THREAD

**Issue by abvdveen** [DivanteLtd/shopware-pwa#1189]
When I create a new project with npx @shopware-pwa/cli@canary init, I get this error after running shopware-pwa dev.

**Comment by mkucmus** [comment]
@abvdveen thanks for reporting this. How long ago did you try the command you mentioned? Because we have fixed it already and it's in the master branch, so the `npx @shopware-pwa/cli@canary init` should work like a charm today I guess :thinking:

**Comment by abvdveen** [comment]
When I posted this, I had just tried on two different systems. Have tried again and still the same. This is the elaborated error:

 FATAL  [shopware-pwa] There is no default language file for en-GB code, please add translation file to locales folder.                            08:07:19

  at extendLocales (node_modules/@shopware-pwa/nuxt-module/dist/nuxt-module.cjs.js:98:11)
  at node_modules/@shopware-pwa/nuxt-module/dist/nuxt-module.cjs.js:343:5
  at Generator.next (<anonymous>)
  at fulfilled (node_modules/@shopware-pwa/nuxt-module/dist/nuxt-module.cjs.js:25:24)

**Comment by abvdveen** [comment]
@mkucmus: F.y.i.: this seems to be fixed. I did a clean install on an empty dir with npx @shopware-pwa/cli@canary init and error is gone :)

**Comment by mkucmus** [comment]
@abvdveen great!

**Comment by super-kamil** [comment]
Error still exists after creating a new theme

**Comment by preeti0109** [comment]
Hello i have install shopware 6.4 and install shopware pwa cancary version as npx @shopware-pwa/cli@canary init.
After adding theme i am getting the same error for There is no default language file for en-GB code, please add translation file to locales folder.

![Screenshot from 2021-07-05 13-16-48](https://user-images.githubusercontent.com/86950633/124436124-4dcacf00-dd93-11eb-9904-c8a48ea3c12b.png)

Any idea for this ?

**Comment by mkucmus** [comment]
@preeti0109 could you describe more details here?
If I get it right you've:
- installed @canary version via CLI - clear
- created new theme via CLI, **inherited from default theme?**, where is it placed?
- did you build your theme using `yarn dev` or `yarn build` before running a project?

please add some information about your environment like node version, OS. Any detail may help us to reproduce the issue 👍🏻
